export type TerminalThemeId =
  | 'auto'
  | 'light'
  | 'dark'
  | 'vscode-dark'
  | 'vscode-light'
  | 'dracula'
  | 'nord'
  | 'monokai'
  | 'solarized-dark'
  | 'solarized-light'
  | 'gruvbox-dark'
  | 'one-dark'
  | 'tokyo-night'
  | 'catppuccin-mocha'
  | 'github-dark';

export interface TerminalTheme {
  id: TerminalThemeId;
  name: string;
  description: string;
  colors: Record<string, string>;
}

export const TERMINAL_THEMES: TerminalTheme[] = [
  {
    id: 'auto',
    name: 'Auto',
    description: 'Follow system theme',
    colors: {}, // Actual colors determined at runtime
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'VibeTunnel default dark',
    colors: {
      background: '#1e1e1e',
      foreground: '#d4d4d4',
      cursor: 'rgb(var(--color-primary))',
      cursorAccent: '#1e1e1e',
      black: '#000000',
      red: '#cd0000',
      green: '#00cd00',
      yellow: '#cdcd00',
      blue: '#0000ee',
      magenta: '#cd00cd',
      cyan: '#00cdcd',
      white: '#e5e5e5',
      brightBlack: '#7f7f7f',
      brightRed: '#ff0000',
      brightGreen: '#00ff00',
      brightYellow: '#ffff00',
      brightBlue: '#5c5cff',
      brightMagenta: '#ff00ff',
      brightCyan: '#00ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'light',
    name: 'Light',
    description: 'Soft light theme',
    colors: {
      background: '#f8f9fa',
      foreground: '#1f2328',
      cursor: 'rgb(var(--color-primary))',
      cursorAccent: '#f8f9fa',
      black: '#24292f',
      red: '#cf222e',
      green: '#1a7f37',
      yellow: '#9a6700',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#da3633',
      brightGreen: '#2da44e',
      brightYellow: '#bf8700',
      brightBlue: '#218bff',
      brightMagenta: '#a475f9',
      brightCyan: '#3192aa',
      brightWhite: '#8c959f',
      selectionBackground: '#0969da',
      selectionForeground: '#ffffff',
      selectionInactiveBackground: '#e1e4e8',
    },
  },
  {
    id: 'vscode-dark',
    name: 'VS Code Dark',
    description: 'Popular theme from Visual Studio Code',
    colors: {
      background: '#1E1E1E',
      foreground: '#D4D4D4',
      cursor: '#AEAFAD',
      cursorAccent: '#1E1E1E',
      black: '#000000',
      red: '#CD3131',
      green: '#0DBC79',
      yellow: '#E5E510',
      blue: '#2472C8',
      magenta: '#BC3FBC',
      cyan: '#11A8CD',
      white: '#E5E5E5',
      brightBlack: '#666666',
      brightRed: '#F14C4C',
      brightGreen: '#23D18B',
      brightYellow: '#F5F543',
      brightBlue: '#3B8EEA',
      brightMagenta: '#D670D6',
      brightCyan: '#29B8DB',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'vscode-light',
    name: 'VS Code Light',
    description: 'Light theme from Visual Studio Code',
    colors: {
      background: '#FFFFFF',
      foreground: '#333333',
      cursor: '#000000',
      cursorAccent: '#FFFFFF',
      black: '#000000',
      red: '#CD3131',
      green: '#00BC7C',
      yellow: '#949800',
      blue: '#0451A5',
      magenta: '#BC05BC',
      cyan: '#0598BC',
      white: '#555555',
      brightBlack: '#666666',
      brightRed: '#CD3131',
      brightGreen: '#14CE14',
      brightYellow: '#B5BA00',
      brightBlue: '#0451A5',
      brightMagenta: '#BC05BC',
      brightCyan: '#0598BC',
      brightWhite: '#A5A5A5',
      selectionBackground: '#ADD6FF',
      selectionForeground: '#333333',
      selectionInactiveBackground: '#E5EBF1',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Classic dark theme',
    colors: {
      background: '#282A36',
      foreground: '#F8F8F2',
      cursor: '#F8F8F2',
      cursorAccent: '#282A36',
      black: '#21222C',
      red: '#FF5555',
      green: '#50FA7B',
      yellow: '#F1FA8C',
      blue: '#BD93F9',
      magenta: '#FF79C6',
      cyan: '#8BE9FD',
      white: '#F8F8F2',
      brightBlack: '#6272A4',
      brightRed: '#FF6E6E',
      brightGreen: '#69FF94',
      brightYellow: '#FFFFA5',
      brightBlue: '#D6ACFF',
      brightMagenta: '#FF92DF',
      brightCyan: '#A4FFFF',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic north-bluish palette',
    colors: {
      background: '#2E3440',
      foreground: '#D8DEE9',
      cursor: '#D8DEE9',
      cursorAccent: '#2E3440',
      black: '#3B4252',
      red: '#BF616A',
      green: '#A3BE8C',
      yellow: '#EBCB8B',
      blue: '#81A1C1',
      magenta: '#B48EAD',
      cyan: '#88C0D0',
      white: '#E5E9F0',
      brightBlack: '#4C566A',
      brightRed: '#BF616A',
      brightGreen: '#A3BE8C',
      brightYellow: '#EBCB8B',
      brightBlue: '#81A1C1',
      brightMagenta: '#B48EAD',
      brightCyan: '#8FBCBB',
      brightWhite: '#ECEFF4',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    description: 'Iconic dark theme from Sublime Text',
    colors: {
      background: '#272822',
      foreground: '#F8F8F2',
      cursor: '#F8F8F0',
      cursorAccent: '#272822',
      black: '#272822',
      red: '#F92672',
      green: '#A6E22E',
      yellow: '#F4BF75',
      blue: '#66D9EF',
      magenta: '#AE81FF',
      cyan: '#A1EFE4',
      white: '#F8F8F2',
      brightBlack: '#75715E',
      brightRed: '#F92672',
      brightGreen: '#A6E22E',
      brightYellow: '#F4BF75',
      brightBlue: '#66D9EF',
      brightMagenta: '#AE81FF',
      brightCyan: '#A1EFE4',
      brightWhite: '#F9F8F5',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    description: 'Precision colors for machines and people',
    colors: {
      background: '#002B36',
      foreground: '#839496',
      cursor: '#839496',
      cursorAccent: '#002B36',
      black: '#073642',
      red: '#DC322F',
      green: '#859900',
      yellow: '#B58900',
      blue: '#268BD2',
      magenta: '#D33682',
      cyan: '#2AA198',
      white: '#EEE8D5',
      brightBlack: '#586E75',
      brightRed: '#CB4B16',
      brightGreen: '#586E75',
      brightYellow: '#657B83',
      brightBlue: '#839496',
      brightMagenta: '#6C71C4',
      brightCyan: '#93A1A1',
      brightWhite: '#FDF6E3',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    description: 'Light variant of the Solarized palette',
    colors: {
      background: '#FDF6E3',
      foreground: '#657B83',
      cursor: '#657B83',
      cursorAccent: '#FDF6E3',
      black: '#073642',
      red: '#DC322F',
      green: '#859900',
      yellow: '#B58900',
      blue: '#268BD2',
      magenta: '#D33682',
      cyan: '#2AA198',
      white: '#EEE8D5',
      brightBlack: '#586E75',
      brightRed: '#CB4B16',
      brightGreen: '#586E75',
      brightYellow: '#657B83',
      brightBlue: '#839496',
      brightMagenta: '#6C71C4',
      brightCyan: '#93A1A1',
      brightWhite: '#FDF6E3',
      selectionBackground: '#268BD2',
      selectionForeground: '#FDF6E3',
      selectionInactiveBackground: '#EEE8D5',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    description: 'Retro groove color scheme',
    colors: {
      background: '#282828',
      foreground: '#EBDBB2',
      cursor: '#EBDBB2',
      cursorAccent: '#282828',
      black: '#282828',
      red: '#CC241D',
      green: '#98971A',
      yellow: '#D79921',
      blue: '#458588',
      magenta: '#B16286',
      cyan: '#689D6A',
      white: '#A89984',
      brightBlack: '#928374',
      brightRed: '#FB4934',
      brightGreen: '#B8BB26',
      brightYellow: '#FABD2F',
      brightBlue: '#83A598',
      brightMagenta: '#D3869B',
      brightCyan: '#8EC07C',
      brightWhite: '#EBDBB2',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    description: 'Atom editor dark theme',
    colors: {
      background: '#282C34',
      foreground: '#ABB2BF',
      cursor: '#528BFF',
      cursorAccent: '#282C34',
      black: '#282C34',
      red: '#E06C75',
      green: '#98C379',
      yellow: '#E5C07B',
      blue: '#61AFEF',
      magenta: '#C678DD',
      cyan: '#56B6C2',
      white: '#ABB2BF',
      brightBlack: '#5C6370',
      brightRed: '#E06C75',
      brightGreen: '#98C379',
      brightYellow: '#E5C07B',
      brightBlue: '#61AFEF',
      brightMagenta: '#C678DD',
      brightCyan: '#56B6C2',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'Clean dark theme inspired by Tokyo city lights',
    colors: {
      background: '#1A1B26',
      foreground: '#A9B1D6',
      cursor: '#C0CAF5',
      cursorAccent: '#1A1B26',
      black: '#15161E',
      red: '#F7768E',
      green: '#9ECE6A',
      yellow: '#E0AF68',
      blue: '#7AA2F7',
      magenta: '#BB9AF7',
      cyan: '#7DCFFF',
      white: '#A9B1D6',
      brightBlack: '#414868',
      brightRed: '#F7768E',
      brightGreen: '#9ECE6A',
      brightYellow: '#E0AF68',
      brightBlue: '#7AA2F7',
      brightMagenta: '#BB9AF7',
      brightCyan: '#7DCFFF',
      brightWhite: '#C0CAF5',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    description: 'Soothing pastel theme for the high-spirited',
    colors: {
      background: '#1E1E2E',
      foreground: '#CDD6F4',
      cursor: '#F5E0DC',
      cursorAccent: '#1E1E2E',
      black: '#45475A',
      red: '#F38BA8',
      green: '#A6E3A1',
      yellow: '#F9E2AF',
      blue: '#89B4FA',
      magenta: '#F5C2E7',
      cyan: '#94E2D5',
      white: '#BAC2DE',
      brightBlack: '#585B70',
      brightRed: '#F38BA8',
      brightGreen: '#A6E3A1',
      brightYellow: '#F9E2AF',
      brightBlue: '#89B4FA',
      brightMagenta: '#F5C2E7',
      brightCyan: '#94E2D5',
      brightWhite: '#A6ADC8',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    description: 'GitHub official dark theme',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      cursor: '#C9D1D9',
      cursorAccent: '#0D1117',
      black: '#484F58',
      red: '#FF7B72',
      green: '#3FB950',
      yellow: '#D29922',
      blue: '#58A6FF',
      magenta: '#BC8CFF',
      cyan: '#39C5CF',
      white: '#B1BAC4',
      brightBlack: '#6E7681',
      brightRed: '#FFA198',
      brightGreen: '#56D364',
      brightYellow: '#E3B341',
      brightBlue: '#79C0FF',
      brightMagenta: '#D2A8FF',
      brightCyan: '#56D4DD',
      brightWhite: '#F0F6FC',
    },
  },
];
